### ISSUE TITLE
Images Error Not Found

### ISSUE THREAD

**Issue by siokas** [schol-io/scholio#4]
Change the img tag in all the project to not include the path (ex. /images/schools) if the image comes from the web. Just put an if the path starts with http.

**Comment by Tsam88** [comment]
done!

**Comment by siokas** [comment]
Μπραβο Χρηστο απ᾽ οτι βλεπω το διόρθωσες το λάθος αλλά 1ον να μην κανεις push στο master (καλύτερα να κανεις μόνο pull request) και 2ον μην κανεις γενικά πολλά commits για τόσο μικρό task. Με πολλά commits είναι πιο δύσκολο να τα διαχειριστούμε σε κάποιο πιθανό λαθος. 

Κατα τα άλλα τέλεια!

**Comment by siokas** [comment]
Τελειο
